# -*- coding: utf-8 -*-
"""SudarshanJajoo_FinalProject_EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbEptAszwjC6jfXoHm1Kk2yRyWYP7aMb

# Predicting Housing Sale prices in Iowa

# **Database Description**
"""

import kagglehub

path = kagglehub.dataset_download("shashanknecrothapa/ames-housing-dataset")

path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.model_selection import cross_val_score
from sklearn.inspection import permutation_importance
import os

dataset_path = '/root/.cache/kagglehub/datasets/shashanknecrothapa/ames-housing-dataset/versions/1'
print(os.listdir(dataset_path))

"""## Preliminary Examination"""

file_path = '/root/.cache/kagglehub/datasets/shashanknecrothapa/ames-housing-dataset/versions/1/AmesHousing.csv'
df = pd.read_csv(file_path)
df.head()

print(df.info())
print("\nMissing Values:\n", df.isnull().sum()[df.isnull().sum() > 0])

df.columns

"""The average sale price is approximately $180,796, with values ranging from $12,789 to $755,000, reflecting a broad spectrum of property types. Homes in the dataset were constructed between 1872 and 2010, with the average year of construction being 1971, and many underwent remodeling or additions around 1984. Lot characteristics reveal an average lot area of 10,147 square feet and a mean lot frontage of 69.22 feet, highlighting the diversity in property sizes. Additional features include average wood deck areas of 93.75 square feet, open porches of 47.53 square feet, and enclosed porches of 23.01 square feet, providing further context on property amenities.

Correlation analysis reveals that Overall Quality (0.799), Above Ground Living Area (0.707), and Garage Capacity (0.648) are the strongest predictors of sale prices. These features emphasize the importance of material and finish quality, living space, and vehicle storage in determining property value. Basement area (Total Bsmt SF) also demonstrates a strong positive correlation (0.632). Conversely, some features, like enclosed porches (-0.129) and kitchens above grade (-0.120), show slight negative correlations with sale prices, suggesting they may detract from a home's overall appeal. Seasonal and luxury features, such as pool areas (0.068) and screen porches (0.112), exhibit weak correlations, indicating a limited impact on pricing in this dataset.

The dataset captures homes sold during a period of significant market fluctuation, with most transactions occurring between 2007 and 2008. This temporal context provides an opportunity to explore trends in property valuation within a mid-sized housing market during this timeframe. However, extreme outliers in features such as sale price and lot area highlight the need for careful preprocessing to ensure robust analysis.
"""

min_values = df[['SalePrice', 'Gr Liv Area', 'Lot Area', 'Garage Area', '1st Flr SF', 'Yr Sold']].min()
max_values = df[['SalePrice', 'Gr Liv Area', 'Lot Area', 'Garage Area', '1st Flr SF', 'Yr Sold']].max()

min_max_values = pd.DataFrame({'Min': min_values, 'Max': max_values})
print(min_max_values)

numerical_features = ['Lot Area', 'Overall Qual', '1st Flr SF',
                     'Total Bsmt SF', 'Garage Area', 'SalePrice']

plt.figure(figsize=(12, 6))
sns.boxplot(data=df[numerical_features])
plt.xticks(rotation=45)
plt.title('Distribution of Key Numerical Features')
plt.show()

"""The box plot above visualizes the distribution of six key numerical features in the Ames Housing dataset, providing significant insights into the dataset's property characteristics. SalePrice displays the widest range, spanning from approximately $12,000 to over $700,000, with a median value around $160,000. The presence of numerous high-value outliers reflects the inclusion of luxury homes or properties with unique features.

Lot Area exhibits substantial variability, with several extreme outliers exceeding 150,000 square feet. Despite these outliers, most properties have lot sizes concentrated between 7,500 and 11,000 square feet, suggesting that the majority of homes in the dataset fall within typical suburban standards. Overall Quality, measured on a scale from 1 to 10, shows a compact distribution with most properties clustering around a median rating of 6, indicating consistently moderate construction quality across homes in the dataset.

Year Built demonstrates a relatively even distribution with few outliers, highlighting that most homes were constructed between 1950 and 2000. Only a small number of homes were built either before 1900 or in very recent years, making the dataset skewed toward mid-century properties. Total Basement Square Footage and Garage Area also exhibit a moderately compact distribution, with few high-value outliers representing homes with significantly larger living or storage spaces.

The visualization underscores the diversity in the dataset, with certain features, such as Lot Area and SalePrice, showing high variability driven by outliers. This variability may influence the performance of predictive models, especially if those outliers are not accounted for during preprocessing.
"""

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='SalePrice', kde=True)
plt.title('Distribution of House Prices')
plt.xlabel('Sale Price ($)')
plt.axvline(df['SalePrice'].mean(), color='red', linestyle='--', label='Mean')
plt.axvline(df['SalePrice'].median(), color='green', linestyle='--', label='Median')
plt.legend()
plt.show()

"""The histogram shows the distribution of house sale prices. The distribution is right-skewed (positively skewed), with most houses concentrated in the lower price ranges and a long tail extending toward higher prices. The median price (green dashed line) is approximately $160,000, while the mean price (red dashed line) is higher at around $180,796, which is typical for right-skewed distributions.
The bulk of house prices falls between $100,000 and $300,000, with the highest frequency occurring around $150,000-$175,000. There are relatively few houses priced above $400,000, and very few outliers extend beyond $600,000, with the maximum price reaching $755,000.
The distribution also shows a clear peak (mode) slightly below the median, with the frequency gradually decreasing on both sides, though more rapidly on the left than on the right. This indicates that while there is significant variation in house prices, there is a strong central tendency around the $150,000-$175,000 range.
"""

# Create a correlation heatmap with adjusted size
plt.figure(figsize=(14, 10))  # Increase the figure size to reduce clutter
sns.heatmap(
    df[numerical_features].corr(),
    annot=True,
    cmap='coolwarm',
    center=0,
    fmt='.2f',  # Limit decimal points for annotations to two
    annot_kws={"size": 8}  # Reduce annotation font size for clarity
)
plt.title('Correlation Heatmap of Key Features', fontsize=14)  # Add a larger, clear title
plt.xticks(rotation=45, fontsize=10)  # Adjust x-axis labels for readability
plt.yticks(fontsize=10)  # Adjust y-axis labels for readability
plt.tight_layout()  # Ensure everything fits without overlap
plt.show()

"""Overall Quality has the strongest correlation with SalePrice (0.80), highlighting its significant influence on property values. Garage Area and Total Basement Square Footage also show relatively strong correlations with SalePrice, at 0.64 and 0.63, respectively, indicating that functional spaces play an important role in determining house prices.

Year Built shows a moderate correlation with SalePrice (0.56), suggesting that newer homes tend to be valued higher, although not as strongly as features like quality or space. On the other hand, Lot Area has the weakest correlation with SalePrice (0.27), meaning that lot size has a relatively minor impact on pricing in this dataset.

The heatmap also highlights some interesting relationships between the features themselves. For example, Overall Quality correlates well with Garage Area (0.56) and Total Basement SF (0.55), indicating that higher-quality homes are often associated with larger garages and basements. There is also a moderate correlation (0.49) between Garage Area and Total Basement SF, showing that these spaces often increase together.

### **Initial Visulization**
"""

numerical_features = ['SalePrice', 'Overall Qual', 'Garage Area', '1st Flr SF']
plt.figure(figsize=(12, 12))
sns.pairplot(df[numerical_features])
plt.suptitle('Scatter Plot Matrix of Key Features', y=1.02)
plt.show()

"""The pairplot provides a comprehensive overview of the relationships between key features in the Ames housing dataset, including SalePrice, Overall Qual, Garage Area, and 1st Flr SF. The diagonal plots represent the distribution of individual features, while the off-diagonal scatterplots illustrate pairwise relationships. The distribution of SalePrice shows a positive skew, with most homes priced under $300,000 and a few outliers above $500,000, likely representing luxury properties. Overall Qual is concentrated between values of 5 and 7, indicating that most homes in the dataset are of average quality. Garage Area and 1st Flr SF have distributions that reflect typical sizes, with most garages ranging from 200 to 1,000 square feet and first-floor areas clustering between 1,000 and 2,000 square feet.

The pairwise scatterplots highlight several important relationships. SalePrice shows a strong positive correlation with Overall Qual and 1st Flr SF, indicating that higher construction quality and larger living areas significantly influence housing prices. The relationship between SalePrice and Garage Area is positive but less pronounced, suggesting that while garage size contributes to price, it is not as impactful as other features. Similarly, higher-quality homes tend to have larger garages and first-floor areas, although there is some variability within mid-range quality ratings. The relationship between Garage Area and 1st Flr SF shows a weak to moderate correlation, reflecting the tendency for larger homes to include more expansive garages.

Overall, this visualization emphasizes the importance of Overall Qual and 1st Flr SF as primary predictors of housing prices, while features like Garage Area provide secondary contributions. The scatterplots and distributions collectively offer valuable insights into the interactions between these features and their impact on sale prices, guiding feature selection and model refinement in predictive analysis.
"""

plt.figure(figsize=(12, 6))
sns.violinplot(x='Overall Qual', y='SalePrice', data=df)
plt.title('Sale Price Distribution by Overall Quality')
plt.xlabel('Overall Quality')
plt.ylabel('Sale Price ($)')
plt.xticks(rotation=0)
plt.show()

"""The violin plot titled demonstrates a clear progression in house prices across quality ratings from 1 to 10. The shape of each "violin" represents the density of houses at different price points, with wider sections indicating more houses at that price level. Lower quality ratings (1-4) show concentrated distributions in the lower price range ($50,000-$150,000) with minimal variation. Middle-range qualities (5-7) display increasing price ranges and wider distributions, indicating more price variability. The highest quality ratings (8-10) exhibit the widest price ranges and highest values, reaching above $800,000, with quality 10 homes showing particularly high price concentrations in the upper ranges."""

plt.figure(figsize=(12, 6))
scatter = plt.scatter(df['1st Flr SF'], df['SalePrice'],
                      c=df['Overall Qual'], cmap='viridis',
                      alpha=0.6)
plt.colorbar(scatter, label='Overall Quality')
plt.title('Sale Price vs 1st Floor SF (colored by Overall Quality)')
plt.xlabel('1st Floor SF')
plt.ylabel('Sale Price ($)')
plt.show()

"""The scatter plot illustrates the relationship between Sale Price and 1st Floor Square Footage, with points colored by Overall Quality. A clear positive trend is evident, showing that homes with larger 1st floor areas tend to have higher sale prices. The color gradient adds an extra layer of insight, indicating that homes with higher quality ratings (depicted in yellow and light green) are not only larger but also command significantly higher prices.

The plot reveals that houses with a 1st Floor SF area greater than 2,000 square feet frequently achieve sale prices exceeding $300,000, especially when their overall quality is rated 8 or higher. On the other hand, smaller homes (less than 1,000 square feet) cluster in the lower price ranges, with most being under $200,000, irrespective of their quality rating. This pattern highlights the importance of both size and quality in determining property value, emphasizing that larger, high-quality homes are seen as more desirable in the Ames housing market.
"""

# Calculate the correlation coefficient
correlation = df['SalePrice'].corr(df['Garage Area'])
print(f"Correlation between Sale Price and Garage Area: {correlation:.2f}")

# Scatter plot to visualize the relationship
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Garage Area', y='SalePrice', data=df, alpha=0.6)
plt.title('Sale Price vs Garage Area', fontsize=14)
plt.xlabel('Garage Area (sq ft)', fontsize=12)
plt.ylabel('Sale Price ($)', fontsize=12)
plt.grid(True)
plt.tight_layout()
plt.show()

"""The scatter plot above illustrates the relationship between Sale Price and Garage Area in square feet for the Ames housing dataset. The correlation coefficient of 0.64 suggests a moderately strong positive relationship, indicating that houses with larger garage areas tend to have higher sale prices.

The plot reveals a concentration of data points around the 400–800 sq. ft. range for garage area, with corresponding sale prices between $100,000 and $300,000. This clustering reflects the typical garage size and price range for most houses in the dataset. As garage size increases beyond 800 sq. ft., sale prices generally rise, with some reaching over $500,000, suggesting that larger garages may be a feature of more expensive homes.

Notably, a few outliers are evident, such as properties with garage areas exceeding 1,200 sq. ft. or with very high sale prices that deviate from the general trend. These outliers likely represent luxury homes or properties with unique characteristics, such as oversized garages tailored to specific needs.

The graph highlights that while garage area significantly impacts sale price, it is not the sole determinant. Other features, such as overall quality or lot area, likely influence pricing and explain the spread of points within each garage size range. This insight underscores the need to consider multiple features in housing price prediction models.
"""

# Calculate the correlation coefficient
correlation_bsmt = df['SalePrice'].corr(df['Total Bsmt SF'])
print(f"Correlation between Sale Price and Total Basement Area: {correlation_bsmt:.2f}")

# Scatter plot to visualize the relationship
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Total Bsmt SF', y='SalePrice', data=df, alpha=0.6, color='teal')
plt.title('Sale Price vs Total Basement Area', fontsize=14)
plt.xlabel('Total Basement Area (sq ft)', fontsize=12)
plt.ylabel('Sale Price ($)', fontsize=12)
plt.grid(True)
plt.tight_layout()
plt.show()

"""The scatter plot illustrates the relationship between Sale Price and Total Basement Area in square feet for houses in the Ames housing dataset. The correlation coefficient of 0.63 indicates a moderately strong positive relationship, suggesting that larger basement areas are associated with higher house prices.

The majority of the data points are clustered between 500 and 2,000 sq. ft. for basement area, with corresponding sale prices ranging between $100,000 and $300,000. This clustering reflects typical basement sizes and price ranges for most houses in the dataset. Notably, as basement size increases beyond 2,000 sq. ft., sale prices generally rise, with some reaching over $500,000. This trend suggests that larger basement areas may be a feature of higher-end properties.

The plot also reveals a few outliers, such as properties with extremely large basements exceeding 4,000 sq. ft. or exceptionally high sale prices. These outliers likely represent unique or luxury properties, where the basement serves a specific purpose, such as entertainment spaces or additional living areas.

Interestingly, while the correlation is positive, there is noticeable dispersion in the data. For example, houses with basement areas of around 1,000 sq. ft. exhibit a wide range of sale prices, indicating that other factors, such as overall quality, location, or additional features, play a significant role in determining house prices. This insight highlights the importance of considering multiple features in predictive models to capture the complexity of the housing market.

"""

# Group by Neighborhood and calculate the average SalePrice
neighborhood_prices = df.groupby('Neighborhood')['SalePrice'].mean().sort_values()

# Plot the relationship
plt.figure(figsize=(12, 8))
sns.barplot(x=neighborhood_prices.index, y=neighborhood_prices.values, palette='viridis')
plt.title('Average Sale Price by Neighborhood', fontsize=16)
plt.xlabel('Neighborhood', fontsize=12)
plt.ylabel('Average Sale Price ($)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""The bar chart highlights the average sale prices of houses across various neighborhoods in the Ames dataset, providing valuable insights into the disparity in property values. The data reveals a clear stratification among neighborhoods, with some areas commanding significantly higher prices than others. This variation reflects the influence of location, amenities, and overall housing quality on property values.

At the lower end of the spectrum, neighborhoods such as MeadowV, IDOTRR, and BrDale have the lowest average sale prices, indicating lower demand or possibly less desirable conditions. These areas may have smaller homes, fewer amenities, or other characteristics that make them less attractive to buyers. In contrast, premium neighborhoods like NoRidge, StoneBr, and NridgHt show average sale prices exceeding $300,000, making them the most expensive areas in the dataset. The higher prices in these neighborhoods could be attributed to larger homes, superior infrastructure, and proximity to desirable amenities.

The chart also highlights neighborhoods with mid-range average sale prices, such as Sawyer, Blueste, and Mitchel, which cluster around $150,000. These neighborhoods likely represent standard housing options that balance affordability with reasonable quality, catering to a broader segment of buyers.

The wide range of average sale prices, from approximately $70,000 in MeadowV to over $300,000 in NoRidge, underscores the diverse real estate landscape in Ames. This visualization not only illustrates the significant impact of location on property values but also provides a useful tool for identifying potential investment opportunities or affordable housing options within the dataset.
"""

df['Sale Date'] = pd.to_datetime(df['Yr Sold'].astype(str) + '-' + df['Mo Sold'].astype(str).str.zfill(2) + '-01')

# Set 'Sale Date' as the index
df.set_index('Sale Date', inplace=True)

# Resample data to monthly frequency and calculate mean price
monthly_prices = df['SalePrice'].resample('M').mean()

# Plot monthly average prices
plt.figure(figsize=(12, 6))
plt.plot(monthly_prices.index, monthly_prices.values)
plt.title('Monthly Average Sale Prices')
plt.xlabel('Date')
plt.ylabel('Average Sale Price')
plt.grid(True)
plt.show()

# Calculate year-over-year price changes
yoy_changes = monthly_prices.pct_change(12)

# Plot year-over-year price changes
plt.figure(figsize=(12, 6))
plt.plot(yoy_changes.index, yoy_changes.values)
plt.title('Year-over-Year Price Changes')
plt.xlabel('Date')
plt.ylabel('YoY Price Change (%)')
plt.grid(True)
plt.show()

# Analyze seasonality
seasonal_avg = df.groupby(df.index.month)['SalePrice'].mean()

plt.figure(figsize=(10, 6))
sns.barplot(x=seasonal_avg.index, y=seasonal_avg.values)
plt.title('Average Sale Price by Month')
plt.xlabel('Month')
plt.ylabel('Average Sale Price')
plt.show()

"""This graph shows the average sale prices of homes over time, from 2006 to mid-2010. There is significant fluctuation in the average sale prices, with a clear trend of declining prices after 2008. Early in the timeline (2006-2007), the market displays volatility with spikes reaching over $220,000, indicating peaks of strong demand or high-value transactions. However, from 2008 onward, there is a noticeable downward trend, aligning with the 2008 financial crisis, which severely impacted the housing market. By mid-2010, the average sale price drops close to $140,000, suggesting persistent economic challenges and reduced market value.

The second graph tracks the year-over-year (YoY) percentage changes in prices from 2007 to mid-2010. Positive values represent price increases, while negative values indicate declines. Early in 2007, there are positive YoY changes, showing market growth. However, from late 2007 through 2008, there is increased volatility, with steep dips into negative territory, reflecting a collapse in home values. The sharp drop near 2009 highlights the recession's peak effect on the housing market, with YoY declines nearing -20% to -30%. Although some minor recoveries appear in 2009 and 2010, the overall trend remains negative, suggesting the market had not fully stabilized.

The third bar chart examines average sale prices by month, aggregated over the observed years. January consistently has the highest average prices, nearing $200,000, while the prices drop during February to April, suggesting seasonal trends in the housing market. Spring and summer months (May to September) show slight increases in sale prices, aligning with the typical seasonality where the real estate market sees more activity and higher demand. Interestingly, prices remain relatively stable in the second half of the year, with slight declines in November and December, potentially due to decreased buying activity during the holiday season.
"""